### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by UtkarshChaurasia** [UtkarshChaurasia/COVID-19-A-boon-for-nature#1]
Readme of the project needs to be updated. Name of project admin and mentors need to be added in the readme.

**Comment by ankitdobhal** [comment]
> Readme of the project needs to be updated. Name of project admin and mentors need to be added in the readme.



> Readme of the project needs to be updated. Name of project admin and mentors need to be added in the readme.
Hey @UtkarshChaurasia !
I have updated Readme check the PR #2 .
Thanks
