### ISSUE TITLE
Learning and summary of Auto Regression Model.

### ISSUE THREAD

**Issue by UtkarshChaurasia** [UtkarshChaurasia/COVID-19-A-boon-for-nature#4]
Update the content section of read me in the Learning folder. Mention the summary of AR Model. If you have any code snippet or implementation then please add the Jupyter notebook containing the code and it's explanation.

**Comment by shiwangi20** [comment]
Hi, Can i work on this issue?

**Comment by UtkarshChaurasia** [comment]
Yeah go ahead!
