### ISSUE TITLE
Learning and summary of Moving Average(MA)

### ISSUE THREAD

**Issue by UtkarshChaurasia** [UtkarshChaurasia/COVID-19-A-boon-for-nature#5]
Update the content section of read me in the Learning folder. Mention the summary of MA Model. If you have any code snippet or implementation then please add the Jupyter notebook containing the code and it's explanation.

**Comment by Jahnavi-Jonnalagadda** [comment]
@UtkarshChaurasia, would like to work on this issue. Could you please assign this to me.

**Comment by shiwangi20** [comment]
@UtkarshChaurasia @Jahnavi-Jonnalagadda can i work on this?

**Comment by Jahnavi-Jonnalagadda** [comment]
@shiwangi20, will be completing this today.

**Comment by Jahnavi-Jonnalagadda** [comment]
@shiwangi20, I will be completing this today.

**Comment by Jyotika999** [comment]
Can i work on this?

**Comment by Jahnavi-Jonnalagadda** [comment]
@Jyotika999, I'm already working on this.
