### ISSUE TITLE
Learning and summary of Augmented Dickey-Fuller(ADF)

### ISSUE THREAD

**Issue by UtkarshChaurasia** [UtkarshChaurasia/COVID-19-A-boon-for-nature#8]
Update the content section of read me in the Learning folder. Mention the summary of Augmented Dickey-Fuller(ADF). If you have any code snippet or implementation then please add the Jupyter notebook containing the code and it's explanation.

**Comment by shiwangi20** [comment]
Hi, if no one is working on this, can i take up this issue?

**Comment by UtkarshChaurasia** [comment]
Sure go ahead!
